### ISSUE TITLE
Code Bugs

### ISSUE THREAD

**Issue by xixy** [aakanksha19/ODETTE#1]
Thanks for your open-sourced project about this work.

However, when running the code, I find some bugs to fix. For example, checkout Line.234 in tester.py, the declaration about model is incorrect and should be modified as follow

`model = EventExtractor(len(list(sent_vocab.keys())), args.emb_size, args.hidden_size, 1, args.dropout, args.bidir, args.model, pos_vocab_size=len(list(pos_vocab.keys())))`

otherwise the code fails because len(list(pos_vocab.keys()))) is recognized as argument for num_layers and the pos_vocab_size is None.

**Comment by aakanksha19** [comment]
Thanks a lot for pointing that out! Looks like that was an issue in both tester.py and da_tester_new.py. I've fixed the bug now, so the code should work without any further issues, but please let me know if you run into something!
