### ISSUE TITLE
What does the arg '10000' stand for?

### ISSUE THREAD

**Issue by xixy** [aakanksha19/ODETTE#4]
Hi, would you check Line.275 in da_tester_new.py? I don't understand what the arg '10000' stand for?
`model = AdversarialEventExtractor(10000, train_batches[0][0].size()[-1], args.hidden_size, 1, args.adv_size, args.adv_layers, args.num_domains, args.adv_coeff, args.dropout, args.bidir, args.model)`

'10000' is clearly the vocab size. But why the vocab size is not len(list(sent_vocab.keys()))?

Thanks!

**Comment by aakanksha19** [comment]
Hi! In line 275, the model being instantiated is a BERT model. Since BERT does not require or use word-level vocabulary, a dummy size of 10000 is being passed as an argument. The BERT models rely on their own subword tokenization process. Hope this clarifies things!
